export { default as Header } from './Header'
export { default as Home } from './Home'
export { default as About } from './About'
export { default as Skills } from './Skills'
export { default as Services } from './Services'
export { default as Portfolio } from './Portfolio'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
